---
- name: Apagar máquinas virtuales en VMware vCenter
  hosts: localhost
  gather_facts: false
  collections:
  vars_files:
      vars/p_variables_prod.yaml
  vars: 
    current_state: "Prendida"

  tasks:

    - name: IF estado  
      debug:
        msg: "La VM está apagada"
      when: vm_state == "powered-on"

    - name: ELSE estado
      debug:
        msg: "La VM está encendida"
      when: vm_state != "powered-on"

    - name: Apagado o Encendido VMs de forma ordenada (Guest Shutdown)
      vmware.vmware.vm_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vm_datacenter }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ item }}"         
        state: "{{ vm_state }}" 
      loop: "{{ vm_list_04 }}"
      register: poweroff_results_vm_list_04
    - name: Obtener vm_id
      set_fact:
        current_state: "Apagada"
      when: vm_state != "powered-on" 

    - name: Resultado del apagado o encendido
      debug:
        msg: >
          VM {{ item.item }} →
          {{ item.changed | ternary(current_state , 'Sin cambios') }}
      loop: "{{ poweroff_results_vm_list_04.results }}"