---
- name: Shutdown ESXi Host gracefully
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars_files:
    vars/p_variables.yaml

  tasks:
    - name: Enter maintenance mode
      vmware_host_maintenance:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        esxi_hostname: "{{ item }}"
        state: present
        timeout: 900
        loop: "{{ esxi_hosts }}"
        register: maintenance_results

    - name: Resultado del modo mantenimiento de los esxi
      debug:
        msg: >
          VM {{ item.item }} →
          {{ item.changed | ternary('maintenance', 'Sin cambios') }}
      loop: "{{ maintenance_results.results }}"
       
    - name: Shutdown ESXi host
      vmware_host_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        esxi_hostname: "{{ item }}"
        state: powered-off
        loop: "{{ esxi_hosts }}"
        register: Shutdown_results
      
    - name: Resultado del apagado de los esxi
      debug:
        msg: >
          VM {{ item.item }} →
          {{ item.changed | ternary('Apagado', 'Sin cambios') }}
      loop: "{{ Shutdown_results.results }}" 